# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_homework', '0002_remove_vote_save_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='save_name',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
