# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_homework', '0005_vote_save_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='students_invited',
        ),
        migrations.AddField(
            model_name='vote',
            name='class_invited',
            field=models.ManyToManyField(to='e_homework.Class'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('小', '小学'), ('初', '初中'), ('高', '高中')], max_length=8),
        ),
    ]
