# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('e_homework', '0006_auto_20160722_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
