# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('e_homework', '0007_auto_20160805_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-class_belong_to'],
                     'permissions': (('students_permission', 'students_permission'),)},
        ),
    ]
