# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_homework', '0008_auto_20160929_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attach_to_questions', models.ManyToManyField(to='e_homework.Question')),
            ],
        ),
    ]
